services:

  api:
    build:
      context: ./backend

    container_name: devflow-api

    environment:
      DATABASE_URL: postgresql+psycopg://devflow:devflow@postgres:5432/devflow
      REDIS_URL: redis://redis:6379/0
      ENVIRONMENT: development
      GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET:-}

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy


  worker:
    build:
      context: ./backend
    container_name: devflow-worker
    command: celery -A app.workers.celery_app:celery_app worker --loglevel=info --concurrency=2
    environment:
      DATABASE_URL: postgresql+psycopg://devflow:devflow@postgres:5432/devflow
      REDIS_URL: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: devflow-postgres

    environment:
      POSTGRES_USER: devflow
      POSTGRES_PASSWORD: devflow
      POSTGRES_DB: devflow

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devflow -d devflow"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: devflow-redis

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
