from pathlib import PurePosixPath

from app.config import Settings, settings
from app.schemas.changed_file import ChangedFile, ScopeSummary, SkippedFile

IGNORED_DIRS = {"vendor", "vendored", "third_party", "third-party", "node_modules",
                ".venv", "venv", "__pycache__", "generated", "_generated", "build", "dist"}
GENERATED_MARKERS = ("@generated", "automatically generated", "auto-generated", "autogenerated", "do not edit")


def select_review_files(files: list[ChangedFile], limits: Settings = settings):
    selected, skipped, total = [], [], 0
    # Stable ordering means identical inputs receive identical scope decisions.
    for file in sorted(files, key=lambda item: item.filename):
        path = PurePosixPath(file.filename.lower())
        patch = file.patch
        reason = None
        if any(part in IGNORED_DIRS for part in path.parts[:-1]):
            reason = "ignored_directory"
        elif path.name.endswith((".lock", ".lock.py")) or path.name in {"poetry.lock", "pipfile.lock"}:
            reason = "lock_file"
        elif path.suffix != ".py":
            reason = "unsupported_extension"
        elif path.name.endswith(("_pb2.py", "_pb2_grpc.py", ".generated.py")) or any(
            marker in (patch or "").lower() for marker in GENERATED_MARKERS
        ):
            reason = "generated_file"
        elif file.status == "removed":
            reason = "removed_file"
        elif not patch:
            reason = "missing_patch"
        elif "\x00" in patch or patch.startswith(("Binary files ", "GIT binary patch")):
            reason = "binary_patch"
        elif len(patch) > limits.max_patch_chars_per_file:
            reason = "max_patch_chars_per_file"
        elif len(selected) >= limits.max_files:
            reason = "max_files"
        elif total + len(patch) > limits.max_total_patch_chars:
            reason = "max_total_patch_chars"
        if reason:
            skipped.append(SkippedFile(filename=file.filename, reason=reason, patch_chars=len(patch or "")))
        else:
            selected.append(file)
            total += len(patch)
    return selected, ScopeSummary(
        limited=bool(skipped), total_files=len(files), selected_files=len(selected), total_patch_chars=total,
        max_files=limits.max_files, max_patch_chars_per_file=limits.max_patch_chars_per_file,
        max_total_patch_chars=limits.max_total_patch_chars, skipped_files=skipped,
    )
