"""create review jobs table

Revision ID: 32f54c571827
Revises: 
Create Date: 2026-09-22 15:54:56.646485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f54c571827'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_name', sa.String(length=255), nullable=False),
    sa.Column('pull_request_number', sa.Integer(), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_name', 'pull_request_number', 'head_sha', name='uq_review_commit')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_jobs')
    # ### end Alembic commands ###
