"""add review job lifecycle fields

Revision ID: 4a20e7825799
Revises: 32f54c571827
Create Date: 2026-09-22 16:11:34.917765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a20e7825799'
down_revision: Union[str, Sequence[str], None] = '32f54c571827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('review_jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint(
        'ck_review_jobs_status', 'review_jobs',
        "status IN ('queued', 'processing', 'completed', 'failed', 'superseded')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_review_jobs_status', 'review_jobs', type_='check')
    op.drop_column('review_jobs', 'completed_at')
    op.drop_column('review_jobs', 'started_at')
    # ### end Alembic commands ###
