"""add review findings

Revision ID: 52dd2fc1dc1b
Revises: 7bf8932e112e
Create Date: 2026-09-24 20:20:29.326022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52dd2fc1dc1b'
down_revision: Union[str, Sequence[str], None] = '7bf8932e112e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_job_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high')", name='ck_findings_severity'),
    sa.CheckConstraint("source IN ('ruff', 'bandit', 'ai')", name='ck_findings_source'),
    sa.CheckConstraint('line_number > 0', name='ck_findings_positive_line'),
    sa.ForeignKeyConstraint(['review_job_id'], ['review_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_review_job_id'), 'findings', ['review_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_review_job_id'), table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###
