"""add review scope and repository metadata

Revision ID: 7bf8932e112e
Revises: bcafb42a7d7b
Create Date: 2026-09-23 19:12:46.384498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bf8932e112e'
down_revision: Union[str, Sequence[str], None] = 'bcafb42a7d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_jobs', sa.Column('github_repository_id', sa.BigInteger(), nullable=True))
    op.add_column('review_jobs', sa.Column('base_sha', sa.String(length=40), nullable=True))
    op.add_column('review_jobs', sa.Column('scope_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_jobs', 'scope_summary')
    op.drop_column('review_jobs', 'base_sha')
    op.drop_column('review_jobs', 'github_repository_id')
    # ### end Alembic commands ###
