"""link webhook delivery to queued review

Revision ID: 9758d7370e8c
Revises: 5dffcfa33589
Create Date: 2026-09-22 19:54:41.162853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9758d7370e8c'
down_revision: Union[str, Sequence[str], None] = '5dffcfa33589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('review_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_webhook_events_review_id', 'webhook_events', 'review_jobs', ['review_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_webhook_events_review_id', 'webhook_events', type_='foreignkey')
    op.drop_column('webhook_events', 'review_id')
    # ### end Alembic commands ###
