"""persist GitHub installation and changed files

Revision ID: bcafb42a7d7b
Revises: 9758d7370e8c
Create Date: 2026-09-23 13:51:35.446271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcafb42a7d7b'
down_revision: Union[str, Sequence[str], None] = '9758d7370e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_jobs', sa.Column('installation_id', sa.BigInteger(), nullable=True))
    op.add_column('review_jobs', sa.Column('changed_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('review_jobs', sa.Column('error_code', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_jobs', 'error_code')
    op.drop_column('review_jobs', 'changed_files')
    op.drop_column('review_jobs', 'installation_id')
    # ### end Alembic commands ###
