"""add durable retry leases

Revision ID: d1c51114d44e
Revises: f59716984cae
Create Date: 2026-09-28 21:02:32.527585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c51114d44e'
down_revision: Union[str, Sequence[str], None] = 'f59716984cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_jobs', sa.Column('last_error', sa.String(length=64), nullable=True))
    op.add_column('review_jobs', sa.Column('lease_token', sa.UUID(), nullable=True))
    op.add_column('review_jobs', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('review_jobs', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('review_jobs', sa.Column('publication_attempt_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('review_jobs', sa.Column('next_publication_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_jobs', 'next_publication_at')
    op.drop_column('review_jobs', 'publication_attempt_count')
    op.drop_column('review_jobs', 'next_attempt_at')
    op.drop_column('review_jobs', 'lease_expires_at')
    op.drop_column('review_jobs', 'lease_token')
    op.drop_column('review_jobs', 'last_error')
    # ### end Alembic commands ###
