"""add github check publication

Revision ID: f59716984cae
Revises: 52dd2fc1dc1b
Create Date: 2026-09-24 23:27:52.997986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f59716984cae'
down_revision: Union[str, Sequence[str], None] = '52dd2fc1dc1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_jobs', sa.Column('github_check_run_id', sa.BigInteger(), nullable=True))
    op.add_column('review_jobs', sa.Column('publication_status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_jobs', 'publication_status')
    op.drop_column('review_jobs', 'github_check_run_id')
    # ### end Alembic commands ###
